[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[rpc_endpoints]
local = "${ERA_TEST_NODE_RPC_URL}"

[invariant]
runs = 25
depth = 10
fail_on_revert = true


# See more config options https://github.com/foundry-rs/foundry/tree/master/config