blank_issues_enabled: true
contact_links:
    - name: Dev Support
      url: https://github.com/ZKsync-Community-Hub/zksync-developers/discussions/
      about: This issue tracker is only for bugs and feature requests. Support is available on Dev Discussions!
