[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./zkout/ConstantNumber.sol/ConstantNumber.json"}]

[fuzz]
no_zksync_reserved_addresses = true

[rpc_endpoints]
local = "${ERA_TEST_NODE_RPC_URL}"
mainnet = "https://mainnet.era.zksync.io:443"
testnet = "https://testnet.era.zksync.dev:443"

[invariant]
runs = 10

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
