[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./zkout/ConstantNumber.sol/ConstantNumber.json"}]

[fuzz]
no_zksync_reserved_addresses = true

[rpc_endpoints]
local = "${ERA_TEST_NODE_RPC_URL}"
mainnet = "https://mainnet.era.zksync.io:443"
testnet = "https://testnet.era.zksync.dev:443"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default.invariant]
runs = 10
depth = 1

[etherscan]
testnet = { key = "PLACEHOLDER", chain = "300", url = "https://api-sepolia-era.zksync.network/api" }
