[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./zkout/ConstantNumber.sol/ConstantNumber.json"}]
libraries = []
solc = "0.8.20"

[profile.default.zksync]
zksolc="1.5.0"
[fuzz]
no_zksync_reserved_addresses = true

[rpc_endpoints]
local = "${ERA_TEST_NODE_RPC_URL}"
mainnet = "https://mainnet.era.zksync.io:443"
testnet = "https://testnet.era.zksync.dev:443"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default.invariant]
runs = 10
depth = 1