name: Governance tests

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

env:
    CARGO_TERM_COLOR: always
    RPC_MAINNET: ${{ secrets.RPC_MAINNET }}
jobs:
  test:
    runs-on: ubuntu-22.04-github-hosted-16core

    steps:  
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            submodules: recursive
            ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            toolchain: nightly-2024-02-06

      - name: Build forge binary
        run: cargo build --release --bin forge

      - name: Clone aave governance v3
        run: git clone https://github.com/Moonsong-Labs/aave-governance-v3.git --depth=1 

      - name: Run tests using built binary
        run: |
          cd aave-governance-v3 
          ../target/release/forge test --zksync
