name: Infrastructure tests

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

env:
    CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-22.04-github-hosted-16core

    steps:  
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            submodules: recursive
            ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            toolchain: nightly-2024-04-28

      - name: Build forge binary
        run: cargo build --release --bin forge

      - name: Clone Aave Delivery Infrastructure
        run: git clone https://github.com/Moonsong-Labs/aave-delivery-infrastructure.git --depth=1 -b ci

      - name: Run tests using built binary
        run: |
          cd aave-delivery-infrastructure
          ../target/release/forge test --zksync --avoid-contracts "*/PayloadScripts.t.sol"
