name: Release-plz

on:
  push:
    branches:
      - main

jobs:

  release:
    uses: matter-labs/zksync-ci-common/.github/workflows/release-plz.yaml@v1
    secrets:
      gh_token: ${{ secrets.RELEASE_TOKEN }}
      cargo_registry_token: ${{ secrets.CRATES_IO_TOKEN }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK_RELEASES }}
